// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: hive.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HiveService_ForceDisconnect_FullMethodName = "/HiveService/ForceDisconnect"
	HiveService_Online_FullMethodName          = "/HiveService/Online"
)

// HiveServiceClient is the client API for HiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HiveServiceClient interface {
	// rpc Connect(ConnectRequest) returns (stream ConnectionStatus) {}
	ForceDisconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	Online(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineResponse, error)
}

type hiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHiveServiceClient(cc grpc.ClientConnInterface) HiveServiceClient {
	return &hiveServiceClient{cc}
}

func (c *hiveServiceClient) ForceDisconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, HiveService_ForceDisconnect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiveServiceClient) Online(ctx context.Context, in *OnlineRequest, opts ...grpc.CallOption) (*OnlineResponse, error) {
	out := new(OnlineResponse)
	err := c.cc.Invoke(ctx, HiveService_Online_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiveServiceServer is the server API for HiveService service.
// All implementations must embed UnimplementedHiveServiceServer
// for forward compatibility
type HiveServiceServer interface {
	// rpc Connect(ConnectRequest) returns (stream ConnectionStatus) {}
	ForceDisconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	Online(context.Context, *OnlineRequest) (*OnlineResponse, error)
	mustEmbedUnimplementedHiveServiceServer()
}

// UnimplementedHiveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHiveServiceServer struct {
}

func (UnimplementedHiveServiceServer) ForceDisconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceDisconnect not implemented")
}
func (UnimplementedHiveServiceServer) Online(context.Context, *OnlineRequest) (*OnlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Online not implemented")
}
func (UnimplementedHiveServiceServer) mustEmbedUnimplementedHiveServiceServer() {}

// UnsafeHiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HiveServiceServer will
// result in compilation errors.
type UnsafeHiveServiceServer interface {
	mustEmbedUnimplementedHiveServiceServer()
}

func RegisterHiveServiceServer(s grpc.ServiceRegistrar, srv HiveServiceServer) {
	s.RegisterService(&HiveService_ServiceDesc, srv)
}

func _HiveService_ForceDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServiceServer).ForceDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiveService_ForceDisconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServiceServer).ForceDisconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HiveService_Online_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServiceServer).Online(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiveService_Online_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServiceServer).Online(ctx, req.(*OnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HiveService_ServiceDesc is the grpc.ServiceDesc for HiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HiveService",
	HandlerType: (*HiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForceDisconnect",
			Handler:    _HiveService_ForceDisconnect_Handler,
		},
		{
			MethodName: "Online",
			Handler:    _HiveService_Online_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hive.proto",
}
